### PR TITLE
Changing the Address to the office to the new address

### PR DESCRIPTION
**Pull request by pdenitto**
Updating the Address to reflect reality - all walking distances were still tied to the old office address on York St.

@edward @kvs

### CODE REVIEW

**Comment by edward** [comment]
Thanks!

Do the tests run green for you locally?

**Comment by kvs** [comment]
`ERROR: Failed to build gem native extension`, and also using Ruby 1.9. This app needs a little dev TLC.

Aside from that, :+1:

**Comment by edward** [comment]
@kvs Ok, I fixed up CI. Rerunning your tests. I’ll merge when green.

**Comment by edward** [comment]
@kvs I also just realized that while it’s good that we’re updating the address, all of the walking times will now be wrong since they were all hard-coded. I’ll open an issue to fix these.

**Pull request merged**
